# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ddfc1128e03cbdbc5301bfd3a2eef4072367586e0045c904027f3d72abf51d995f017e820413544ec6c565ce0d4ee95ce82f3b8b2399d152009218aa2592a2

test:
  secret_key_base: 623975b5cf22ffb9130c3f9ada798d1c10caeedec6f87f8ad468a3f1082fb3b8f53fd8c4cd49f3284427db30808a860fb34ba81d09b4bd36c8927349ddb7cb41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
